### PR TITLE
Adding infrared spectra intensity

### PR DESCRIPTION
**Pull request by ajz34**
Hi devs!

I saw the issue https://github.com/pyscf/pyscf/issues/678 and I tried to make an infrared spectra intensity implementation.
Should be able to evaluate RHF/RKS/UHF/UKS IR intensities, as long as hessian is available.
Seems that there is plan to implement more molecular properties. Hope this PR does not collide with existing efforts :joy_cat:

### CODE REVIEW

**Comment by sofroniewn** [comment]
Wow! This is great from my perspective. I just tried it on an optimized acetone molecule and I get what I think are some reasonable looking values. I can also confirm that the vibrational frequencies here are the same as those gotten from a `thermo.harmonic_analysis` call.

The API I used to generate the following was

```python
from pyscf import gto
from pyscf.prop.infrared.rhf import Infrared

mol = gto.Mole().fromfile('acetone_opt_pyscf.raw')
mf = mol.RHF().run()
mf_ir = Infrared(mf).run()
mf_ir.plot_ir()
```

which worked great

image

Thanks so much @ajz34 - that was also an incredibly fast turnaround time if you did that just after seeing my post!!

**Comment by sofroniewn** [comment]
I should add I'm afraid it's beyond my current computational chemistry expertise to review the code or confirm the accuracies of the caclulations

**Comment by AMDALI** [comment]
> Wow! This is great from my perspective. I just tried it on an optimized acetone molecule and I get what I think are some reasonable looking values. I can also confirm that the vibrational frequencies here are the same as those gotten from a `thermo.harmonic_analysis` call.
> 
> The API I used to generate the following was
> 
> ```python
> from pyscf import gto
> from pyscf.prop.infrared.rhf import Infrared
> 
> mol = gto.Mole().fromfile('acetone_opt_pyscf.raw')
> mf = mol.RHF().run()
> mf_ir = Infrared(mf).run()
> mf_ir.plot_ir()
> ```
> 
> which worked great
> 
> image
> 
> Thanks so much @ajz34 - that was also an incredibly fast turnaround time if you did that just after seeing my post!!

Hello
Im interssting to use plot_ir for my work I use VS code and I cant plot my work in in it.
is there any way to do it please

**Comment by AMDALI** [comment]
Hello
Im interssting to use plot_ir for my work I use VS code and I cant plot my work in in it.
is there any way to do it please

**Comment by sunqm** [comment]
Great feature. I should merge it early.

**Comment by hebrewsnabla** [comment]
> Hello Im interssting to use plot_ir for my work I use VS code and I cant plot my work in in it. is there any way to do it please

If you follow example 06, you can change `fig.show()` to `fig.savefig('xxx.png')`, and then the figure can be saved.

**Comment by PeterXiaoGuo** [comment]
nice features

**Pull request merged**
